### ISSUE TITLE
Not converting complete Image.

### ISSUE THREAD

**Issue by vishwas097** [metafloor/zpl-image#1]
let id= document.getElementById("image");
    let res = imageToZ64(id,{notrim:true,black:56, rotate:'I',height:id['height']});
    let zpl = "^XA^LH0,0^FWN^PON^PMN^LRN^FO10,10^GFA,"+ res['length'] +","+ res['length'] +","+ res['rowlen'] +","+ res['z64'] +" ^XZ".

Hello, I have a problem here. Can anyone tell why only the half of the image is converting. That it is only converting width upto 192 px.

**Comment by metafloor** [comment]
Without seeing the html and css that is affecting the image, I can only recommend that you step into `imageToZ64()` with the debugger and see what is happening here:

```
    cvs.width  = +img.width || img.offsetWidth;
    cvs.height = +img.height || img.offsetHeight;
    ctx.drawImage(img, 0, 0);
```

What values are being assigned to `cvs.width` and `cvs.height`?
