### ISSUE TITLE
Are white pixels being eaten up?

### ISSUE THREAD

**Issue by jmbldwn** [metafloor/zpl-image#11]
I'm rendering my label in a canvas element.  I'm drawing black on white for the label contents.

I'm calling `imageToZ64(canvas);` to generate the ZPL from my canvas.

What's weird is the ZPL appears to drop all white pixels on the top and left of my canvas, so to get my label to print properly in the center I have to put a black border around the perimeter of the canvas.

Is this expected behavior, or am I doing something wrong?

**Comment by metafloor** [comment]
Set `notrim` to `true` in the options object.  If you look at the code, you will see the following callout for the option:

```
    // Create a monochome image, cropped to remove padding.
    // The return is a Uint8Array with extra properties width and height.
    let mono = monochrome(rgba, width, height, +opts.black || 50, opts.notrim);
```
