### ISSUE TITLE
Use in Angular?

### ISSUE THREAD

**Issue by patrickchoi** [metafloor/zpl-image#2]
Been trying to use this in Angular but having trouble getting it identified as a library. Not sure you have any experience with this platform but any idea how to import the library?

**Comment by metafloor** [comment]
Have you installed the package via `npm install zpl-image --save` so that your project dependencies are updated?  I do not use angular but my understanding is that browserify or webpack will then use those dependencies to build a deployment bundle for angular.

**Comment by patrickchoi** [comment]
I installed with `npm install zpl-image --save`

Used this at the top of the .ts file `import * as zpl from 'zpl-image';`

Getting a new error:

```
ERROR ReferenceError: pako is not defined
    at rgbaToZ64 (vendor.js:341223)
    at Object.imageToZ64 (vendor.js:341178)
```

**Comment by metafloor** [comment]
I would try `npm install pako --save` as well.

**Comment by patrickchoi** [comment]
No change, still `pako is not defined`

**Comment by patrickchoi** [comment]
As a workaround I copied all the functions in `zpl-image.js` and pasted them in the .ts file. Removed `function` and prefixed all the function calls with `this.`. 

Not sure why zpl-image couldn't find pako but I found that `import * as pako from 'pako';` works fine, could access those functions inside .ts.

Working perfectly, got the ZPL output.

**Comment by msirghi** [comment]
@patrickchoi, do you still have an example of this?

**Comment by metafloor** [comment]
If someone is willing to provide a typescript definition file for project, I will be happy to include it.
